#!/bin/sh

set -e
exec 2>&1

e=0

gnome-desktop-testing-runner -l Flatpak | while read t; do
	t="${t%% *}"

	case "$t" in
		(Flatpak/test-builder.sh.test)
			# has more dependencies
			continue
			;;
	esac

	gnome-desktop-testing-runner "$t" < /dev/null || e=$?
done

exit "$e"
