#!/usr/bin/dh-exec

debian/org.freedesktop.Flatpak.pkla     var/lib/polkit-1/localauthority/10-vendor.d/
etc/X11/Xsession.d
etc/profile.d/
lib/systemd/system/flatpak-system-helper.service
usr/bin/flatpak
usr/libexec/flatpak-portal
usr/libexec/flatpak-session-helper
usr/libexec/flatpak-system-helper
usr/lib/systemd/user/dbus.service.d/flatpak.conf
usr/lib/systemd/user/flatpak-portal.service
usr/lib/systemd/user/flatpak-session-helper.service
usr/share/bash-completion
usr/share/dbus-1/services
usr/share/dbus-1/system-services
usr/share/dbus-1/system.d
usr/share/flatpak
usr/share/gdm/env.d
usr/share/locale/*/LC_MESSAGES/flatpak.mo
usr/share/polkit-1/actions
usr/share/polkit-1/rules.d
usr/share/zsh/site-functions/_flatpak   usr/share/zsh/vendor-completions
<!nodoc> usr/share/man/man1
<!nodoc> usr/share/man/man5
<!nodoc> usr/share/doc/flatpak/docbook.css
<!nodoc> usr/share/doc/flatpak/flatpak-docs.html
